name: miaplpy-env
channels:
  - conda-forge
dependencies:
  - c-compiler
  - python>=3.9
  - cartopy
  - cvxopt
  - rasterio
  - dask>=1.0
  - dask-jobqueue>=0.3
  - defusedxml
  - h5py
  - lxml
  - matplotlib
  - numpy
  - pip
  - pyproj
  - scikit-image
  - scipy
  - gdal
  - mintpy
  - isce2
  - cython
  - setuptools
  - pulp
  - pyaps3>=0.3
  - pykml>=0.2
  - pyresample
  - pysolid